export const user = require('../../assets/user.png')
export const userWhite = require('../../assets/user_white.png')
export const back = require('../../assets/back.png')
export const lion = require('../../assets/lion.png')
export const fish = require('../../assets/fish.png')
export const crocodile = require('../../assets/crocodile.png')
export const unicorn = require('../../assets/unicorn.png')

export const lionWhite = require('../../assets/lion_white.png')
export const fishWhite = require('../../assets/fish_white.png')
export const crocodileWhite = require('../../assets/crocodile_white.png')
export const unicornWhite = require('../../assets/unicorn_white.png')
